### ISSUE TITLE
Too poor to sign up

### ISSUE THREAD

**Issue by Bloody2** [hightouch67/hightouch67.github.io#6]
I cannot afford to pay even more bills, so i decided to not have a mobile phone. I cannot sign on because these steemit ELITE IDIOTS demand to send me an SMS, which i simply cannot send or receive. I only have email.

I guess steemit is only for the 1% elite banksters, but not for the poor. Bye now..

**Comment by Bloody2** [comment]
Oh and btw., even if i HAD a SMS-capable phone, my phone number is a PRIVATE MATTER. What else do they want me to tell them - THE LENGTH OF MY PENIS, PERHAPS?

**Comment by skzap** [comment]
Hard to understand, but each steem account actually requires a bit of cryptocurrency as a form of stake to be able to be able to vote, publish content, etc. SteemIt corp pays for these account creation delegations in exchange for your phone number, in order to verify your identity and not give 2 accounts to the same person.

If you want an account without a phone number, you can. Provided you can also afford a bit of crypto. A STEEM account needs about 5 STEEM attached to it to be able to work. You can use this website to buy your own steem account from another cryptocurrency like BTC or LTC: https://anon.steem.network/

If you already have a steem account, you can create another steem account through this tool: https://v2.steemconnect.com/accounts/create

No one cares about your penis size btw
